// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/svcgrpc/cacheservice.proto

package svcgrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRecordRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordRequest) Reset()         { *m = CreateRecordRequest{} }
func (m *CreateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordRequest) ProtoMessage()    {}
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{0}
}

func (m *CreateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordRequest.Unmarshal(m, b)
}
func (m *CreateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordRequest.Merge(m, src)
}
func (m *CreateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordRequest.Size(m)
}
func (m *CreateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordRequest proto.InternalMessageInfo

func (m *CreateRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateRecordRequest) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type CreateRecordResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordResponse) Reset()         { *m = CreateRecordResponse{} }
func (m *CreateRecordResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRecordResponse) ProtoMessage()    {}
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{1}
}

func (m *CreateRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordResponse.Unmarshal(m, b)
}
func (m *CreateRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordResponse.Marshal(b, m, deterministic)
}
func (m *CreateRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordResponse.Merge(m, src)
}
func (m *CreateRecordResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRecordResponse.Size(m)
}
func (m *CreateRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordResponse proto.InternalMessageInfo

func (m *CreateRecordResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateRecordResponse) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type AppendRecordRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRecordRequest) Reset()         { *m = AppendRecordRequest{} }
func (m *AppendRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRecordRequest) ProtoMessage()    {}
func (*AppendRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{2}
}

func (m *AppendRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRecordRequest.Unmarshal(m, b)
}
func (m *AppendRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRecordRequest.Marshal(b, m, deterministic)
}
func (m *AppendRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRecordRequest.Merge(m, src)
}
func (m *AppendRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AppendRecordRequest.Size(m)
}
func (m *AppendRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRecordRequest proto.InternalMessageInfo

func (m *AppendRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppendRecordRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AppendRecordResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRecordResponse) Reset()         { *m = AppendRecordResponse{} }
func (m *AppendRecordResponse) String() string { return proto.CompactTextString(m) }
func (*AppendRecordResponse) ProtoMessage()    {}
func (*AppendRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{3}
}

func (m *AppendRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRecordResponse.Unmarshal(m, b)
}
func (m *AppendRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRecordResponse.Marshal(b, m, deterministic)
}
func (m *AppendRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRecordResponse.Merge(m, src)
}
func (m *AppendRecordResponse) XXX_Size() int {
	return xxx_messageInfo_AppendRecordResponse.Size(m)
}
func (m *AppendRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRecordResponse proto.InternalMessageInfo

func (m *AppendRecordResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type GetRecordRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordRequest) Reset()         { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()    {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{4}
}

func (m *GetRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest.Unmarshal(m, b)
}
func (m *GetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest.Merge(m, src)
}
func (m *GetRecordRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest.Size(m)
}
func (m *GetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest proto.InternalMessageInfo

func (m *GetRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type MessageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StatisticResponse struct {
	RecordCount          int32    `protobuf:"varint,1,opt,name=recordCount,proto3" json:"recordCount,omitempty"`
	ActiveConnections    int32    `protobuf:"varint,2,opt,name=activeConnections,proto3" json:"activeConnections,omitempty"`
	LastUpdate           string   `protobuf:"bytes,3,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticResponse) Reset()         { *m = StatisticResponse{} }
func (m *StatisticResponse) String() string { return proto.CompactTextString(m) }
func (*StatisticResponse) ProtoMessage()    {}
func (*StatisticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_710d2811f9d15a8a, []int{7}
}

func (m *StatisticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticResponse.Unmarshal(m, b)
}
func (m *StatisticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticResponse.Marshal(b, m, deterministic)
}
func (m *StatisticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticResponse.Merge(m, src)
}
func (m *StatisticResponse) XXX_Size() int {
	return xxx_messageInfo_StatisticResponse.Size(m)
}
func (m *StatisticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticResponse proto.InternalMessageInfo

func (m *StatisticResponse) GetRecordCount() int32 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *StatisticResponse) GetActiveConnections() int32 {
	if m != nil {
		return m.ActiveConnections
	}
	return 0
}

func (m *StatisticResponse) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRecordRequest)(nil), "service.CreateRecordRequest")
	proto.RegisterType((*CreateRecordResponse)(nil), "service.CreateRecordResponse")
	proto.RegisterType((*AppendRecordRequest)(nil), "service.AppendRecordRequest")
	proto.RegisterType((*AppendRecordResponse)(nil), "service.AppendRecordResponse")
	proto.RegisterType((*GetRecordRequest)(nil), "service.GetRecordRequest")
	proto.RegisterType((*MessageResponse)(nil), "service.MessageResponse")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*StatisticResponse)(nil), "service.StatisticResponse")
}

func init() {
	proto.RegisterFile("internal/svcgrpc/cacheservice.proto", fileDescriptor_710d2811f9d15a8a)
}

var fileDescriptor_710d2811f9d15a8a = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x5b, 0xa5, 0x21, 0xc3, 0x47, 0xdb, 0x6d, 0x85, 0x8c, 0x05, 0xa8, 0x5a, 0x10, 0xaa,
	0x04, 0xb2, 0x11, 0x9c, 0x40, 0xe2, 0x90, 0x1a, 0xc4, 0x29, 0x17, 0x07, 0x2e, 0xdc, 0xb6, 0xeb,
	0x51, 0x62, 0x91, 0x78, 0x97, 0xdd, 0x71, 0xa4, 0x9c, 0xf9, 0x4b, 0xfc, 0x40, 0xd6, 0x8e, 0xb3,
	0x72, 0x3e, 0x50, 0xb8, 0xed, 0xcc, 0xe4, 0xbd, 0x37, 0x79, 0xcf, 0x03, 0x2f, 0x8a, 0x92, 0xd0,
	0x94, 0x62, 0x96, 0xd8, 0x85, 0x9c, 0x18, 0x2d, 0x13, 0x29, 0xe4, 0x14, 0x2d, 0x9a, 0x45, 0x21,
	0x31, 0xd6, 0x46, 0x91, 0x62, 0xfd, 0xb6, 0xe4, 0x1f, 0xe0, 0x32, 0x35, 0x28, 0x08, 0x33, 0x94,
	0xca, 0xe4, 0x19, 0xfe, 0xaa, 0xd0, 0x12, 0x3b, 0x87, 0x93, 0x9f, 0xb8, 0x0c, 0x83, 0xeb, 0xe0,
	0x66, 0x90, 0xd5, 0xcf, 0xba, 0x43, 0x34, 0x0b, 0x8f, 0x5d, 0xa7, 0x97, 0xd5, 0x4f, 0xfe, 0x11,
	0xae, 0x36, 0xa1, 0x56, 0xab, 0xd2, 0xe2, 0x7f, 0x61, 0x87, 0x70, 0x39, 0xd4, 0x1a, 0xcb, 0xfc,
	0x90, 0x6c, 0x08, 0xfd, 0x39, 0x5a, 0x2b, 0x26, 0xd8, 0xc0, 0x07, 0xd9, 0xba, 0xe4, 0x31, 0x5c,
	0x6d, 0x52, 0xb4, 0xf2, 0x8f, 0xe1, 0xd4, 0x92, 0xa0, 0xca, 0x36, 0x34, 0xf7, 0xb2, 0xb6, 0xe2,
	0x2f, 0xe1, 0xfc, 0x2b, 0xd2, 0x01, 0x3d, 0xfe, 0x1a, 0xce, 0x46, 0x2b, 0x01, 0x4f, 0xd8, 0x59,
	0x21, 0xd8, 0x5c, 0xa1, 0x0f, 0xbd, 0x2f, 0x73, 0x4d, 0x4b, 0xfe, 0x3b, 0x80, 0x8b, 0xb1, 0x93,
	0x29, 0x2c, 0x15, 0xd2, 0x03, 0xaf, 0xe1, 0xbe, 0x69, 0xe4, 0x52, 0x55, 0x95, 0xd4, 0x80, 0x7b,
	0x59, 0xb7, 0xc5, 0xde, 0xc0, 0x85, 0x90, 0x54, 0x2c, 0x30, 0x55, 0x65, 0x89, 0xee, 0xe5, 0x70,
	0xad, 0x4d, 0xbb, 0x03, 0xf6, 0x1c, 0x60, 0x26, 0x2c, 0x7d, 0xd7, 0xb9, 0x33, 0x3d, 0x3c, 0x69,
	0x76, 0xe9, 0x74, 0xde, 0xfd, 0x39, 0x86, 0xb3, 0xa1, 0x31, 0x62, 0x79, 0x2b, 0x2c, 0xe6, 0x69,
	0x9d, 0x3a, 0x1b, 0xc1, 0x83, 0x6e, 0x48, 0xec, 0x69, 0xbc, 0xfe, 0x10, 0xf6, 0xc4, 0x1e, 0x3d,
	0xfb, 0xc7, 0x74, 0xf5, 0x87, 0xf8, 0x51, 0x4d, 0x37, 0x26, 0x65, 0xb0, 0xf5, 0xa8, 0x43, 0xb7,
	0x27, 0xce, 0x0e, 0xdd, 0xbe, 0xa4, 0x1c, 0xdd, 0x27, 0x78, 0xe8, 0x32, 0xf1, 0xce, 0x59, 0xf6,
	0xc8, 0x23, 0x1a, 0x63, 0xa3, 0xc8, 0xd7, 0x3b, 0xf6, 0x3a, 0xf8, 0x67, 0x18, 0xf8, 0x48, 0xd9,
	0x13, 0xff, 0xd3, 0xed, 0x98, 0xa3, 0xd0, 0x8f, 0xb6, 0xb2, 0xe5, 0x47, 0x6f, 0x83, 0xdb, 0x9b,
	0x1f, 0xaf, 0x26, 0x05, 0x4d, 0xab, 0xbb, 0x58, 0xaa, 0x79, 0xf2, 0x4d, 0xd8, 0xf1, 0xc8, 0x9d,
	0x8c, 0xd6, 0xc9, 0xf6, 0x21, 0xdd, 0x9d, 0x36, 0xc7, 0xf3, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0xa6, 0xb8, 0x78, 0x63, 0x03, 0x00, 0x00,
}
